### ISSUE TITLE
Error in serializing with JSONExt in persistant memory store.

### ISSUE THREAD

**Issue by dmachi** [persvr/perstore#28]
In tracing a bug, I discovered that JSONExt.stringify() in memory.js was improperly serializing my data objects.  An Object like (from console.log):

``` javascript
 { state: 'processing',
  keywords: [],
  people: [ { type: 'person', val: '2016252856702' } ],
  exported: false,
  held: false,
  startDate: Wed, 27 Jun 2012 20:43:50 GMT,
  endDate: Wed, 27 Jun 2012 20:43:50 GMT,
  documentCount: 0,
  processingStatus: 0,
  createdBy: [ 'system' ],
  createdOn: Wed, 27 Jun 2012 20:43:59 GMT,
  id: 6726200953126 } 

```

was is serialized (with JSONExt.stringify()) as:
{"state":"processing","keywords":[],"people":[undefined],.......

I modified the code to use JSON.stringify (node's), and it gets:
{"state":"processing","keywords":[],"people":[{"type":"person","val":"2016252856702"}],.....

Is there any explanation of this behavior outside of a bug in the serializer and is there any reason to not defer to the env (eg, jsonext handles circular references..though is not an an issue for me))?

**Comment by neonstalwart** [comment]
this isn't an answer for why the code doesn't defer to the environment but... i believe the serialization issue was fixed in e9ccfa1

**Comment by dmachi** [comment]
Thanks, I'll check that out and see if it fixes things for me.  I think the reason perstore doesn't use the environmental JSON is because its a streaming parser.

Dustin

**Comment by dmachi** [comment]
Confirming the fix.
