### ISSUE TITLE
perstore npm dependencies

### ISSUE THREAD

**Issue by dmachi** [persvr/perstore#31]
When trying to install perstore (v 0.3.0 & 0.3.1) there is a failure caused by the json-schema dependencies.  Perstore is requesting >=0.2.1, but only 0.2.0 exists in npm.  Could you publish 0.2.1 to npm?

**Comment by kriszyp** [comment]
OK, should be published now.

**Comment by dmachi** [comment]
Thanks Kris, that took care of it.

Dustin
