### ISSUE TITLE
directives not passed when using .add() in facet.js

### ISSUE THREAD

**Issue by dmachi** [persvr/perstore#33]
In facet.js' construction.post method, if (!directives.id), the call to this.add doesn't pass the directives object (even if there are other directives).  Unless there is some reason to specifically exclude this, it should be 'return this.add(props, directives)' instead of 'return this.add(props)'.

**Comment by neonstalwart** [comment]
do you mean this https://github.com/persvr/perstore/commit/40c8a51d5b53eb89d1104e88404d935422e62727 ;)
