### ISSUE TITLE
http://en.wikipedia.org/wiki/Indexed_Database_API

### ISSUE THREAD

**Issue by ghost** [persvr/perstore#4]
The Indexed Database API, or Indexed DB (formerly WebSimpleDB).

You might want to update your docs to reflect this now.

Looks like al the browsers are going to do  Indexed Database API - even Microsoft

**Comment by kriszyp** [comment]
Yes, this is the API that Perstore is based on. Are you meaning that you just want me to make sure that is explicitly referenced in the docs? Sounds like a good idea, I didn't realize I forgot to link to it...

**Comment by ghost** [comment]
yes just to make it clear, because there have been so many attempts at web db with different names, so its important to be clear in this case.

cheers

ged

**Comment by kriszyp** [comment]
Should be updated now.
