### ISSUE TITLE
coerce is a little over zealous

### ISSUE THREAD

**Issue by deanlandolt** [persvr/perstore#7]
it looks like the patching of json-schema's coerce is a little over zealous -- it will coerce for required values that don't actually have keys, which causes inserts that should fail to succeed with, for instance, an empty string

**Comment by kriszyp** [comment]
So undefined shouldn't be coerced?

**Comment by deanlandolt** [comment]
well, void 0 should probably, sure...but !key in object shouldn't be, if you know what i'm saying...

it forces _all_ keys to exist (even the required ones) and creates false positives in schema validation

**Comment by deanlandolt** [comment]
and shouldn't it be an opt-in? like, shouldn't you have to have a coerce: true member on your schema descriptor?

**Comment by kriszyp** [comment]
Does this fix it?
https://github.com/kriszyp/commonjs-utils/commit/f9ed9028dfdcf33a3bf616229ef55dd47ad23cf2

**Comment by deanlandolt** [comment]
perfect...if you think it's better to coerce by default -- i guess it doesn't hurt in a postel kinda way, perhaps a "coerce" config setting would also be useful...just a thought, but this works for me
